target-version = "py39"
line-length = 120
src = ["src"]

[lint]
select = ["E", "W", "F", "I", "UP", "B", "SIM", "RUF"]
ignore = ["E501", "UP007", "UP045", "SIM105"]

[format]
quote-style = "double"
indent-style = "space"
